name: qhub-starters
channels:
- conda-forge
dependencies:
# general
- pip

# jupyterhub/jupyterlab
- nb_conda_kernels
- ipython > 7
- jupyter-server-proxy
- jupyterlab-git
- ipywidgets
- jupyterlab
- jupyter_client
- jupyter_console
- jupyterhub
- nodejs
- nbconvert
- nbval
- dask_labextension

# dask
- dask==2.14.0
- distributed
- dask-gateway=0.6.1

# numerical
- numba
- numpy
- pandas

# s3 utits
- s3fs
- boto3

# viz tools
- panel
- param
- graphviz

- nbdime

# testing, docs, linting
- pytest
-pip:
  - hypothesis
  - flake8
  - sphinx
  - pytest-cov
  - black
  - isort
  - importnb
  - python-language-server
  - jupyter-starters
  - jupyter-lsp
  - jupytext